name: CI

on:
  push:
    branches: [ 'master' ]
  pull_request:

env:
  GRADLE_OPTS: >
    -Dorg.gradle.daemon=false
    -Dorg.gradle.vfs.watch=false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
